server:
   port: 8091
   context-path: /demo-spb
spring:
  application:
    name: demo-spb
  session:
    store-type: redis
  redis:
    database: 0
#    host: 192.168.168.137
#    port: 6380
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
#    sentinel:
#      master: mymaster
#      nodes: 192.168.168.137:26379,192.168.168.137:26380
    cluster:
      nodes: 192.168.168.137:7001,192.168.168.137:7002 ,192.168.168.137:7003,  192.168.168.137:7004,  192.168.168.137:7005 ,192.168.168.137:7006




#spring.redis.host=192.168.168.137
#spring.redis.port=6380

# spring session基本配置
#spring.session.store-type=redis


########################################################
###REDIS (RedisProperties) redis基本配置；
########################################################
# database name
#spring.redis.database=0
# server host1 单机使用，对应服务器ip
#spring.redis.host=127.0.0.1
# server password 密码，如果没有设置可不配
#spring.redis.password=
#connection port  单机使用，对应端口号
#spring.redis.port=6379
# pool settings ...池配置
#spring.redis.pool.max-idle=8
#spring.redis.pool.min-idle=0
#spring.redis.pool.max-active=8
#spring.redis.pool.max-wait=-1
# name of Redis server  哨兵监听的Redis server的名称
#spring.redis.sentinel.master=mymaster
# comma-separated list of host:port pairs  哨兵的配置列表
#spring.redis.sentinel.nodes=127.0.0.1:26379,127.0.0.1:26479,127.0.0.1:26579